# Generated by Django 3.2.10 on 2023-09-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_leave',
            name='data',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
