# Generated by Django 3.2.10 on 2023-09-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_course_session_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
    ]
