# Generated by Django 3.2.10 on 2023-09-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_alter_feedback_feedback_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
