# Generated by Django 3.2.10 on 2023-09-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0006_rename_name_course_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustamuser',
            name='profile_pic',
            field=models.ImageField(upload_to='Media/profile_pic'),
        ),
    ]
