# Generated by Django 3.2.10 on 2023-09-10 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0008_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Session_Year_id',
            new_name='session_Year_id',
        ),
    ]
