# Generated by Django 3.2.10 on 2023-09-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0008_student_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_feedback',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
