# Generated by Django 3.2.10 on 2023-09-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0012_alter_subject_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
