# Generated by Django 3.2.10 on 2023-10-04 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0014_alter_course_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='staff',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='studentapp.staff'),
            preserve_default=False,
        ),
    ]
